### ISSUE TITLE
Wrong Hyperlink

### ISSUE THREAD

**Issue by yntpdotme** [BhairaviSanskriti/My-DevOps-Journey#3]
In Terraform Repository second link is wrong.

I should like this : 

Resources that I am using to learn Terraform-
   1.  [HashiCorp Certified: Terraform Associate 2023](https://www.udemy.com/course/terraform-beginner-to-advanced/)
   2.  [Terraform Documentation](https://developer.hashicorp.com/terraform/docs)

**Comment by BhairaviSanskriti** [comment]
Thank you, Akash, for pointing it out!
I've updated the link.
